[colors]
primary.background = "#282828"
primary.foreground = "#ebdbb2"

normal.black = "#282828"
normal.red = "#cc241d"
normal.green = "#98971a"
normal.yellow = "#d79921"
normal.blue = "#458588"
normal.magenta = "#b16286"
normal.cyan = "#689d6a"
normal.white = "#a89984"

bright.black = "#928374"
bright.red = "#fb4934"
bright.green = "#b8bb26"
bright.yellow = "#fabd2f"
bright.blue = "#83a598"
bright.magenta = "#d3869b"
bright.cyan = "#8ec07c"
bright.white = "#ebdbb2"

