[colors]
primary.background = "#fbf1c7"
primary.foreground = "#3c3836"

# Normal colors
normal.black = "#fbf1c7"
normal.red = "#cc241d"
normal.green = "#98971a"
normal.yellow = "#d79921"
normal.blue = "#458588"
normal.magenta = "#b16286"
normal.cyan = "#689d6a"
normal.white = "#7c6f64"

# Bright colors
bright.black = "#928374"
bright.red = "#9d0006"
bright.green = "#79740e"
bright.yellow = "#b57614"
bright.blue = "#076678"
bright.magenta = "#8f3f71"
bright.cyan = "#427b58"
bright.white = "#3c3836"
